name: Plot Image Comparison

on:
  pull_request:
    branches:
      - main

jobs:
  compare-plots:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout feature branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --trusted-host pypi.python.org --no-cache-dir

    - name: Install ImageMagick (for diff images)
      run: sudo apt-get install -y imagemagick

    - name: Run visualization scripts on feature branch
      run: |
        mkdir -p feature_plots
        for script in scripts/*.py; do
          echo "Running $script on feature branch..."
          PYTHONPATH=$(pwd) python "$script" --output_dir feature_plots || echo "Warning: $script failed"
        done

    - name: Upload feature images
      uses: actions/upload-artifact@v4
      with:
        name: feature-plots
        path: feature_plots

    - name: Stash changes and checkout main branch
      run: |
        git stash --include-untracked
        git checkout origin/main

    - name: Run visualization scripts on main branch
      run: |
        mkdir -p main_plots
        for script in scripts/*.py; do
          echo "Running $script on main branch..."
          PYTHONPATH=$(pwd) python "$script" --output_dir main_plots || echo "Warning: $script failed"
        done

    - name: Upload main images
      uses: actions/upload-artifact@v4
      with:
        name: main-plots
        path: main_plots

    - name: Checkout back to feature branch
      run: git checkout -

    - name: Compare images
      run: |
        mkdir -p diffs
        python scripts/image_diff.py main_plots feature_plots diffs || true
        echo "Image diff completed."

    - name: Upload image diffs (always)
      uses: actions/upload-artifact@v4
      with:
        name: image-diffs
        path: diffs
